### ISSUE TITLE
conflicts between gggenomes and gggenes

### ISSUE THREAD

**Issue by zhaoxvwahaha** [thackl/gggenomes#106]
Hi,

The following 2 commands work well when I only install gggenes, but after installed the gggenomes, the command didn't work and get errors:
> p<-ggplot(da, aes(xmin = start, xmax = end, y =molecule, fill = gene, label = gene))
> p+geom_gene_arrow(arrow_body_height = unit(10, "mm"),arrowhead_height = unit(10, "mm"),arrowhead_width = unit(2, "mm"),alpha=0.8,colour="white")+geom_gene_label(height = grid::unit(8, "mm"), grow = FALSE)+theme_genes()+scale_x_continuous(breaks=seq(0, 35000, 4000))
**Error in UseMethod("pull_genes") : 
  no applicable method for 'pull_genes' applied to an object of class "data.frame"
In addition: Warning message:
Ignoring unknown parameters: height, grow**

**Comment by iimog** [comment]
Did you load both `gggenomes` and `gggenes` prior to these commands? If so, in which order? Did you see any warning messages when running the respective `library` commands?
