### ISSUE TITLE
Zoom sequence

### ISSUE THREAD

**Issue by hkaspersen** [thackl/gggenomes#111]
Hello, and thank you for developing this brilliant package!

I was wondering if it was possible to zoom into a specific region of interest, based on either the genetic neighborhood around a gene by name, or simply xlim?

Thanks in advance!

**Comment by thackl** [comment]
Hi Håkon,

yes, you can! Have a look at [`focus()`](https://thackl.github.io/gggenomes/reference/focus.html) and see below for a few simple examples

``` r
library(tidyverse)
library(gggenomes)

# from https://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/009/738/455/GCA_009738455.1_ASM973845v1/
ecoli_genes <- read_feats("GCA_009738455.1_ASM973845v1_genomic.gbff")

# all genes are too many for useful plot
p <- gggenomes(ecoli_genes) +
  geom_seq() +
  geom_gene() + geom_gene_tag(aes(label=name))

# zoom in based on gene name
p %>% focus(name == "metH")
```
![image](https://user-images.githubusercontent.com/9363087/153683734-0c592fbd-cae5-493b-bd4d-a81b43da963b.png)

```r
p %>% focus(name == "metH", .expand = c(1e4, 3e4))
```
![image](https://user-images.githubusercontent.com/9363087/153684152-9c01bbf3-7872-4e50-9dbb-69d263f4a103.png)

```r
# works with multiple hits - each locus becomes a new seq
p %>% focus(str_detect(name, "nag")) 
# see .max_dist to control whether close hits are considered to be part of the
# same locus, and .locus_score/.locus_filter to further filter which of those
# loci to show
```
![image](https://user-images.githubusercontent.com/9363087/153683780-23251ce4-8532-4bc9-b21b-68d6d6214071.png)

```r
# make each locus its own bin
p %>% focus(str_detect(name, "nag"), .locus_bin="locus") 
```
![image](https://user-images.githubusercontent.com/9363087/153683986-fb525054-bb5f-4706-84a1-42f8f99a8856.png)

```r
# zoom in by coordinate table
zoom_to <- tibble(seq_id="CP046527", start=2150000, end=2200000)
p %>% focus(.loci = zoom_to)
```

![image](https://user-images.githubusercontent.com/9363087/153684199-99186003-ce4d-4814-a8e9-77a60257c450.png)

**Comment by hkaspersen** [comment]
Thanks, this worked perfectly!
