### ISSUE TITLE
Mapping metadata to label

### ISSUE THREAD

**Issue by hkaspersen** [thackl/gggenomes#114]
Hello! 
I am having some troubles with adding metadata to the figures made by gggenomes. 
I would like to do something like this:

```
gggenomes(seqs = is_seqs, genes = all_is_gff, links = is_aln_data) +
  geom_seq() +
  geom_bin_label(data = metadata,
                 mapping = aes(label = country))
```
Where I swap out the bin label to a variable I have in some other data frame (or if it can be mapped from one of the dataframes needed for gggenomes). Is this possible in any way?

**Comment by thackl** [comment]
Hi Håkon,

good question. It is definitely possible but as of now probably not as easy as it should be. `geom_bin_label` uses data derived from the sequence table. In theory you can make any data from seqs available to `geom_bin_label`.

```{r fig.height=2}
s0 <- tibble(
  seq_id = c("a1", "a2", "b1"),
  bin_id = c("A", "A", "B"),
  length = c(1000, 2000, 3000),
  country = c("Norway", "Norway", "Sweden")
)

p1 <- gggenomes(seqs=s0) + geom_seq()
p1 + geom_bin_label()
```
![image](https://user-images.githubusercontent.com/9363087/158360717-bbf28f69-a6bc-401e-b481-8c2dc15afd78.png)

Add additional variables from seqs to bins - granted hard to guess unless you know.

```{r fig.height=2}
p1 + geom_bin_label(aes(label=country)) # doesn't work b/c 
p1 %>% pull_bins() # country is not present in internal bin table
p1 %>% pull_bins(.group=vars(country)) # but it can be included
p1 + geom_bin_label(aes(label=country), data=bins(.group=vars(country)))
```
![image](https://user-images.githubusercontent.com/9363087/158360739-b3f68bf1-7746-4c88-b5cc-321afa961fca.png)

It probably would be good to implement the following in future versions. This should be closest to what you suggested. Feel free to comment!

For now, you can just copy and paste the code to make it work for you as well.

```{r fig.height=2}
# something like
bins_with_meta <- function (..., .group = vars(), .meta = NULL){
    dots <- quos(...)
    function(.x, ...) {
        b <- pull_bins(.x, !!!dots, .group = .group)
        if(!is.null(.meta)){
          b <- left_join(b, .meta)
        }
        b
    }
}

meta <- tibble(
  bin_id = c("A", "B"),
  country = c("Norway", "Sweden"),
  year=2022)

gggenomes(seqs=s0) + geom_seq() +
  geom_bin_label(
    aes(label=paste(bin_id, "\n", country, year)),
    data=bins_with_meta(.meta = meta), expand_left = 0.4)
```
![image](https://user-images.githubusercontent.com/9363087/158360920-0d31dfb3-565e-4f22-8bb5-f42e3294f30b.png)

**Comment by hkaspersen** [comment]
Thanks, this works well!
I would also like to know how to change the font of the text in the `geom_bin_label`, as it does not seem to be affected by `theme( text = element_text(family = "Open Sans"))`?

**Comment by thackl** [comment]
Interesting. I would have thought this would work. Internally geom_bin_label just calls geom_text. I'll need to look into it...

**Comment by thackl** [comment]
Ok, so changing the font is actually even easier: `geom_bin_label(family = "Open Sans")`. I don't know why/how theme->text does not work, but it also does not work with a regular ggplot+geom_text. theme->text only seems to affect axis labels etc, i.e. items related to the plot theme, not the geoms...
