### ISSUE TITLE
Add read_alitv() to context-specific read_* functions

### ISSUE THREAD

**Issue by thackl** [thackl/gggenomes#12]
I've added _smart_ read_* functions (read_seqs/read_feats/read_links, ...) with automatic detection of input formats. These functions determine format-specific read_* functions such as `read_alitv` based on file extensions and the given _context_ (seqs/feats/links/...). For example `read_seqs(.gbk)` will interpret .gbk in context "seqs" as format "seq_len" and call `read_seq_len(.gbk)` to parse sequence length information, while `read_feats(.gbk)` will interpret .gbk in context "feats" as format "gbk" and call `read_gbk(.gbk)` to read in genes, etc.

read_alitv currently returns a list of tables already representing the three different contexts the .json file can be read in. It should be quite straight-forward to make alitv files readable via `read_seqs/feats/links`. 

Have a look at `gggenomes_global$file_formats` (global.R) which holds a list of file extensions, formats and contexts known to gggenomes, and used by the smart read functions. You can just add context-specific alitv-formats to `seqs` and `feats`. And you will have to add a new `links` context. So far, that wasn't necessary because for all other formats "links" and "feats" context had the same parser (blast tab files for example).  Note, the name of the format should be identical to the suffix of the `read_` function. So you might have to add the format alitv_seqs,  alitv_genes and alitv_links (or whatever is appropriate), and could just add quick function aliases ala `read_alitv_seqs <- function(...) read_alitv(...)[["seqs"]]` to make `read_seqs(.json)` work.

If you think, .json is not specific to alitv, you can add it to the format "ambiguous". Every extension in this group requires the user to explicitly provide the format...

Oh, and you should put all read_alitv functions etc. in their own file.

Also, this is all still quite experimental, so let me know if you think it is bull or similar ;)

**Comment by iimog** [comment]
This makes a lot of sense. I'll go for it. One thing I'm not sure about is whether to use the format "ambiguous". The json format is certainly not unique to AliTV. However, gggenomes currently doesn't support any other input data in json format. So I think we could interpret any json as AliTV for now but at the risk of having to move it to ambiguous later and breaking backwards compatibility. What do you think @thackl ?

**Comment by thackl** [comment]
Yes, I think there is an issue with the format. Your second code line says `Reading as alitv`, which would call `read_alitv` but you probably want to have `Reading as alitv_seqs` to call `read_alitv_seqs`. I think you are currently feeding the output list of `read_alitv` directly to the map function in all three calls - always causing the same error.

That said, this kind of makes me wonder if the way I've said this up so far, actually makes sense - actually, I think it is definitely flawed. Obviously, it would make more sense to have the format for `read_seqs("alitv.json")` to be "alitv", and have the `read_seqs` function somehow add the right context... I need to think about this some more...

**Comment by iimog** [comment]
You were right. Calling `alitv_seqs` instead of `alitv` fixes it :tada: 
At least for seqs and feats. Links are still interpreted as genes (as you already mentioned in the initial issue text). Anyway, I'll wait until you decided on how you want these smart functions to be handled. Should be straightforward for `alitv` then.

**Comment by thackl** [comment]
resolved by #37
