### ISSUE TITLE
A question regarding synteny

### ISSUE THREAD

**Issue by Rahimlou** [thackl/gggenomes#122]
Just for my understanding, is it possible to show synteny for certain genes (i.e. some part of the genomes)? What function can be used to zoom a specific region in several genomes?

**Comment by thackl** [comment]
Yes, that is possible. The function to do that is [focus](https://thackl.github.io/gggenomes/reference/focus.html). You can do something like this:

```
# full genomes
p1 <- gggenomes(emale_genes, emale_seqs) %>%
 add_sublinks(emale_prot_ava) +
 geom_seq() + geom_gene() + geom_gene_tag(aes(label=name)) + geom_link()
p1
```
![a](https://user-images.githubusercontent.com/9363087/161395971-761b5830-bd89-4b47-ab24-3c5f96d14638.png)

```
# zoom in on major capsid protein
p1 %>% focus(name=="MCP", .expand=2000)
```
![b](https://user-images.githubusercontent.com/9363087/161395978-1f1f0f67-0b54-4693-ba03-4fbd992a2dc1.png)
