### ISSUE TITLE
Changing color of links

### ISSUE THREAD

**Issue by Marlon751** [thackl/gggenomes#123]
Hi. 
I was wondering is it possible to change the color of the geom_link(). I would like to achieve something like this:

![question_gggenome](https://user-images.githubusercontent.com/63800031/165077476-aa33ac1d-1e06-418e-aaba-8002af4aa48a.png)

**Comment by thackl** [comment]
Hi, not sure I fully understand - might be useful to post some of your code. In general, it is definitely possible to change the fill/color of links, for example:
```
gggenomes(emale_genes) %>% add_clusters(emale_cogs) +
  geom_link(aes(fill=cluster_id))
```
![image](https://user-images.githubusercontent.com/9363087/165083320-b0c63dbd-275f-4570-8201-796835b753b0.png)

Assuming you know that and tried something with `add_clusters()`, one issue you might have come across is that the following doesn't work, i.e. metadata associated with clusters is not added to links. Then you would be quite right, that should work. I'll try to add that soon. 
```
emale_cogs
gggenomes(emale_genes) %>% add_clusters(emale_cogs) +
  geom_link(aes(fill=cluster_size))

### FAILS
```

A quick workaround could be to replace `cluster_id` in your cluster data.frame with whatever labels you want to color your links by:
```
# just randomly assign for coloring example
emale_cogs2 <- emale_cogs %>%
  mutate(cluster_id = sample(c("many", "single"), length(cluster_id), replace = T))

gggenomes(emale_genes) %>% add_clusters(emale_cogs2) +
  geom_link(aes(fill=cluster_id))
```
![image](https://user-images.githubusercontent.com/9363087/165083855-8776558c-041e-49cf-b096-26642ab31903.png)

**Comment by Marlon751** [comment]
Thank you very much!
