### ISSUE TITLE
changing shape of gene features？

### ISSUE THREAD

**Issue by Tonny-zhou** [thackl/gggenomes#125]
Dear author,
Thank you for this amazing visualization tool！I have a question, i.e., weather we could change the shape of the element like gene by ourself, which has already been applied in the genoplotr package.

Yours,
Tonny

**Comment by Tonny-zhou** [comment]
> You can modify the style of elements like genes using the `shape` parameter: See [documentation and examples](https://thackl.github.io/gggenomes/reference/geom_gene.html). However, only different variants of arrows are currently possible.

I found that the shape parameter is applied for all elements. Could this parameter be put into the aesthetic mappings function aes?  If this is done, i could applied different shapes to different elements like different functional genes.

**Comment by thackl** [comment]
Hm, I'm not sure. Have the feeling this could be tricky...
