### ISSUE TITLE
working example 

### ISSUE THREAD

**Issue by madhubioinfo** [thackl/gggenomes#126]
Hi i'm trying to use gggenomes,  I can't reproduce any visualizations or data frames for the given example data. Do you have tutorial or documentation for reproducing the data? 

I tried using this https://thackl.github.io/gggenomes/articles/emales.html , its broken can you please provide some examples  also point me to some tutorial ?

**Comment by thackl** [comment]
Hi, sorry, yes the tutorial is out of date, but everything in here should work:
https://thackl.github.io/gggenomes/articles/gggenomes.html

And you can find examples for every function in the reference:
https://thackl.github.io/gggenomes/reference/index.html

To plot genes, for example:
https://thackl.github.io/gggenomes/reference/geom_gene.html
