### ISSUE TITLE
Overlapping text lables

### ISSUE THREAD

**Issue by code-acc** [thackl/gggenomes#130]
Hi there! Is there any way like geom_text_repel for overlapping labels?
Here is the plot where I have overlapping labels:

![image](https://user-images.githubusercontent.com/57204282/196246788-30b738e9-52ca-4e6d-8815-1fcf9a0a5d94.png)

And this is the code:

```gggenome <- gggenomes(seqs=SeqTrack, genes=GeneTrack)  
gggenome +
  geom_seq(size=1) +         # draw contig/chromosome lines
  geom_bin_label(size = 4) +   # label each sequence 
  geom_gene(aes(fill=gene), size=3) +        # draw genes as arrow
  geom_gene_tag(aes(label=gene), nudge_y=0.2, check_overlap = FALSE, hjust = 0.1) +
  theme(axis.text.x = element_text(size=12), legend.position = "none")

**Comment by thackl** [comment]
I haven't directly implemented that in gggenomes, but you can use ggrepel to do it:

```{r}
library(gggenomes)

s0 <- tibble(
  seq_id = "A",
  length = 5000
)

g0 <- tibble(
  seq_id = "A",
  start=c(1000, 1500, 1550),
  end=start+50,
  gene=c("fooo", "baaar", "baaaz")
)

gggenomes(g0, s0) +
  geom_seq() + geom_gene() +
  geom_gene_tag(aes(label=gene))

```
![image](https://user-images.githubusercontent.com/9363087/196645163-4cd436d2-4261-4caa-9c08-30427047a7b0.png)

```{r}
library(ggrepel)
gggenomes(g0, s0) +
  geom_seq() + geom_gene() +
  geom_text(aes(x=(x+xend)/2, y=y+.1, label=gene, color="overlapping"), data=genes(),
                  hjust=0, vjust=0, angle=45) +
  geom_text_repel(aes(x=(x+xend)/2, y=y+.2, label=gene, color="repelled"), data=genes(),
                  hjust=0, vjust=0, angle=45, direction = "x")

```

![image](https://user-images.githubusercontent.com/9363087/196645142-31c8d6db-f2f3-4e6e-b471-d425c92c5d69.png)

Check out https://ggrepel.slowkow.com/articles/examples.html#align-labels-on-the-top-or-bottom-edge-1 for additional ideas to draw lines between genes and tags, etc...

**Comment by code-acc** [comment]
Thank you so much! Really helpful!
