### ISSUE TITLE
geom_link new error

### ISSUE THREAD

**Issue by MaximePolicarpo** [thackl/gggenomes#133]
Hi ! 

I am encountering a strange error since today, while running the exact same code that worked few days ago. 

I have three tibble objects for the seqs, genes and links layers :
p <- gggenomes(seqs=my_seqs, genes=my_genes, links=my_links)  

But when I try to plot it , I get the following error messages: 

p + geom_seq() + geom_gene() + geom_link(aes(fill=OGG, color=OGG))

Error in `geom_link()`:
! Problem while converting geom to grob.
Error occurred in the 3rd layer.
Caused by error in `link_to_poly()`:
! object 'new_data_frame' not found

When trying to plot the graph without the link, however, works perfectly fine :
p + geom_seq() + geom_gene() 

Did anyone encounter the same error recently ?

Here is the full code to reproduce this error : 

my_seqs_ <- read.table("github_cluster_id_arranged.txt", sep=",")
colnames(my_seqs) <- c("bin_id", "seq_id", "length")
my_seqs <- tibble(my_seqs)

my_genes <- read.table("github_seq_clustered_infos_ogg_ordered.csv", sep=",")
colnames(my_genes) <-  c("seq_id", "start", "end", "gene_name", "strand")
my_genes <- tibble(my_genes)

my_links <- read.table("github_link_table.txt", sep=",")
colnames(my_links) <-  c("seq_id", "start", "end", "seq_id2", "start2","end2", "OGG")
my_links <- tibble(my_links)

p <-   gggenomes(seqs=my_seqs, genes=my_genes, links=my_links) 
p + geom_seq() + geom_gene() + geom_link(aes(fill=OGG, color=OGG))

Thanks for any help provided,
Cheers,

Maxime 
[github_cluster_id_arranged.txt](https://github.com/thackl/gggenomes/files/10175513/github_cluster_id_arranged.txt)
[github_link_table.txt](https://github.com/thackl/gggenomes/files/10175514/github_link_table.txt)
[github_seq_clustered_infos_ogg_ordered.csv](https://github.com/thackl/gggenomes/files/10175515/github_seq_clustered_infos_ogg_ordered.csv)

**Comment by thackl** [comment]
Reinstalling gggenomes should fix this (#131). It's caused by an update to ggplot v3.4.0+

**Comment by MaximePolicarpo** [comment]
Thank you a lot ! I reinstalled gggenomes and restarted Rstudio and it now works perfectly fine ! 

All the best,

Maxime
