### ISSUE TITLE
Installation error 

### ISSUE THREAD

**Issue by Angel-Popa** [thackl/gggenomes#140]
Hi, 

I am trying to install gggenome but get this error while installing the dependencies: 

`> devtools::install_github("thackl/thacklr")
Downloading GitHub repo thackl/thacklr@HEAD
These packages have more recent versions available.
It is recommended to update all of them.
Which would you like to update?

1: All                                  
2: CRAN packages only                   
3: None                                 
4: ggtree (3.6.2 -> 431ec37bc...) [Bioc]

Enter one or more numbers, or an empty line to skip updates: 3
Error: Failed to install 'thacklr' from GitHub:
  Multiple results for CXX11FLAGS found, something is wrong.FALSE`

How can I fix this issue?

**Comment by thackl** [comment]
Hi Angel,

that's an odd error, not sure what might cause this. Can you install other packages with devtools or is this specific to installing thacklr?

**Comment by Angel-Popa** [comment]
It seems the error is with install_github and not with the package. I tried to install BHS and got this error at the end: 

`Error: Failed to install 'brms' from GitHub: Multiple results for CXX11FLAGS found, something is wrong.FALSE`

**Comment by Angel-Popa** [comment]
Okay, I found the solution to the issues (it is similar to a report in the [Rstan github page](https://github.com/stan-dev/rstan/issues/866).

As the error described initially, I had multiple CXX11FLAGS. These flags are found in the `Makevars.win` file in windows. To find them, you can run the following: 

```file.edit(file.path(Sys.getenv("HOME"), ".R", "Makevars.win"))```

And remove duplicated flags. 

I'll close this issue as it does not relate to gggenomes and it is also solved.
