### ISSUE TITLE
Move deps from Depends to Imports?

### ISSUE THREAD

**Issue by lionel-** [thackl/gggenomes#142]
Hello. I noticed that all your dependencies are in the `Depends:` section of your `DESCRIPTION` file. This unnecessarily causes all the dependencies to be attached to the search path after a `library(gggenomes)`. By convention, dependencies should be in `Imports:` unless necessary (sometimes ggplot2 is added to Depends). See https://r-pkgs.org/dependencies-mindset-background.html#sec-dependencies-imports-vs-depends for more about this.

**Comment by thackl** [comment]
Hi Lionel, yes you are of course right! I think this is related to me not having done a proper job using `::`, `importFrom`, etc. when I started to dabble in writing R packages. I need do a proper code-clean up soon!

**Comment by thackl** [comment]
Note to self - the move itself is super easy, literally move packages to `Imports:` and add `#' @import` to files for roxygen to put it in `NAMESPACE`. However, that still leaves things messy. Check out [`library(conflicted)`](https://www.tidyverse.org/blog/2018/06/conflicted/) to make calls to functions from other packages explicit.
