### ISSUE TITLE
Setting coordinates to visualise part of the genome

### ISSUE THREAD

**Issue by samrthakur** [thackl/gggenomes#146]
Hello,

I wanted to compare a common locus across different genomes but at variable positions (also sometimes occurring in the plasmids, sometimes in the chromosome). Would it be possible to to set the coordinates for each contig for different assemblies to just compare that particular locus instead of comparing the entire contigs?

Thanks
Samriddhi

**Comment by thackl** [comment]
Hi Samriddhi,

check out https://thackl.github.io/gggenomes/reference/focus.html. You can either zoom in on features of interest, e.g. genes with same name or so on different contigs, or with `.loci=coordinates.dataframe` provide locations directly.
