### ISSUE TITLE
Errors when running read_feats command

### ISSUE THREAD

**Issue by fusho96** [thackl/gggenomes#149]
Platform: Ubuntu 22.04.2 LTS, R ver. 4.3.0,
when running the command in getting started, the results were like this:

> g0 <- read_feats(ex("emales/emales.gff"))
Reading 'gff3' with `read_gff3()`:
* file_id: emales [/usr/local/lib/R/site-library/gggenomes/extdata/emales/emales.gff]
Error in `map2()`:
ℹ In index: 1.
ℹ With name: emales.
Caused by error in `map()`:
ℹ In index: 1.
Caused by error in `!str_length(r) || is.na(r)`:
! 'length = 3' in coercion to 'logical(1)'
Run `rlang::last_trace()` to see where the error occurred.

Is there any way to solve this issue?

**Comment by thackl** [comment]
Interesting, I don't get anything like that on my still R-4.1.2 system, then there are similar warnings in the online documentation built on R 4.2 (https://thackl.github.io/gggenomes/reference/read_tracks.html) and for your with R-4.3 system it seems to cause an error...  Will look into it asap.

**Comment by thackl** [comment]
Just pushed new code. Should work after reinstalling gggenomes.

**Comment by fusho96** [comment]
Thanks a lot for the quick response.
I got the same error when reinstalling gggenomes.
Well, I tried to rollback the R version to 4.1, and it worked.
Thanks for providing the advice.
