### ISSUE TITLE
Draw a combined plot with ggtree and gggenomes

### ISSUE THREAD

**Issue by WRran-Hydrogen** [thackl/gggenomes#158]
Dear @thackl 

Mapping genomes with **gggenomes** is very convenient and trendy, but adding a clustering tree to a large number of genome maps is also of some use, can **ggtree** be used in conjunction with **gggenomes**? This would also allow for sorting the **geom_bin_label** plotted by **gggenomes**

Best！

**Comment by thackl** [comment]
Yes, absolutely. Check out the `pick_by_tree()` examples here: https://thackl.github.io/gggenomes/reference/pick.html

**Comment by WRran-Hydrogen** [comment]
This is a very good function, if I knew this function earlier I do not have to sort genome map and then use illustrator to manually splice the tree file, but the function is still not perfect in that there is no complete genome is not fully aligned branches, but it is good enough to use. Thanks to the author!
![image](https://github.com/thackl/gggenomes/assets/117963364/96674992-4a9a-4f1c-a910-e6df24932832)

**Comment by thackl** [comment]
That's because both of your plots have slightly different y-scales. You can match them up with `scale_y_continuous(expand...)` and/or https://ggplot2.tidyverse.org/reference/expand_limits.html. See here for a bit more complex example https://thackl.github.io/ggtree-composite-plots
