### ISSUE TITLE
Error in Installation

### ISSUE THREAD

**Issue by eylulkepcen** [thackl/gggenomes#170]
Hello, I am trying to install gggenomes to R 4.3.1, but I keep getting the error:
```
> devtools::install_github("thackl/gggenomes")
Downloading GitHub repo thackl/gggenomes@HEAD
Error in utils::download.file(url, path, method = method, quiet = quiet,  : 
  download from 'https://api.github.com/repos/thackl/gggenomes/tarball/HEAD' failed
```
Then I tried to install other packages through devtools and it worked. What can be the issue here?

**Comment by thackl** [comment]
Hm, very odd. Just tried it myself and worked ok. What happens if you open `https://api.github.com/repos/thackl/gggenomes/tarball/HEAD` in your browser. This should download tar.gz of the package.

**Comment by eylulkepcen** [comment]
It downloads the file, then when I want to install the package using the tar.gz, it gives the output: 

`install.packages("~/Downloads/thackl-gggenomes-f29495a.tar", repos = NULL)
Error in install.packages : type == "both" cannot be used with 'repos = NULL'`

**Comment by thackl** [comment]
What version of devtools do you have?

**Comment by eylulkepcen** [comment]
I'm sorry, this line was missing during devtools installation: 

`devtools::install_github("hadley/devtools")`

Now the problem is solved after running it. Thank you!
