### ISSUE TITLE
Error in eval(`_inherit`, env, NULL): object 'Guides' not found.

### ISSUE THREAD

**Issue by xiahui625649** [thackl/gggenomes#179]
`gggenomes(emale_genes, emale_seqs, emale_tirs, emale_ava) +
  geom_seq() + geom_bin_label() +                  # chromosomes and labels
  geom_feat(size=8) +                              # terminal inverted repeats
  geom_gene(aes(fill=strand), position="strand") + # genes
  geom_link(offset = 0.15)                         # synteny-blocks`

> Error in eval(`_inherit`, env, NULL): object 'Guides' not found
ggplot2=3.5.0
gggenomes=1.0.0

**Comment by thackl** [comment]
I saw this kind of error only once after I upgraded and before I restarted my R. Can you try that and see if the problem persists?
