### ISSUE TITLE
Error when loading emales.fna with https://github.com/thackl/gggenomes/blob/HEAD/vignettes/emales.Rmd

### ISSUE THREAD

**Issue by tr31zh** [thackl/gggenomes#187]
When executing command from articles section:
```R
emale_seqs <- read_fai("emales.fna") %>%
    tidyr::extract(seq_desc, into = c("emale_type", "is_typespecies"), 
        "=(\\S+) \\S+=(\\S+)",
        remove=F, 
        convert=T) %>%
    dplyr::arrange(emale_type, length)
```

We get the following error:
```R
Error in dplyr::arrange(., emale_type, length) : 
Caused by error:
! `..2` must be a vector, not a primitive function.
```

Related to:
- https://github.com/thackl/gggenomes/issues/153
- https://github.com/thackl/gggenomes/issues/53

**System**: macbook pro 14.2.1 (23C71)
**R** version: 4.4.0 clean install
**tidyr**: 1.3.1
**dplyr**: 1.1.4

**Comment by iimog** [comment]
The code in this vignette is from an earlier version of `gggenomes`, there are currently no resources to update the code for the latest version. Therefore, there is this disclaimer at the top of the page:

> DISCLAIMER: I’ve created this demo with an early version of gggenomes. Not all of the code will function with current releases. However, the general workflow both with respect to the external tools and gggenomes code is still valid and this demo should therefore be understood as an hopefully inspiring guide - not as an exactly reproducible code example (Those kind of examples you can find in the examples sections of the documentation).
