### ISSUE TITLE
CRAN policy violation - fail gracefully on unavailable internet resources

### ISSUE THREAD

**Issue by thackl** [thackl/gggenomes#197]
Dear maintainer,

Got emails from CRAN

> Please see the problems shown on [<https://cran.r-project.org/web/checks/check_results_gggenomes.html>](https://cran.r-project.org/web/checks/check_results_gggenomes.html).
> Please correct before 2024-08-31 to safely retain your package on CRAN.
> It seems we need to remind you of the CRAN policy:
> 'Packages which use Internet resources should fail gracefully with an informative message if the resource is not available or has changed (and not give a check warning nor error).' This needs correction whether or not the resource recovers.

> For the record, the current failure is
> Error: processing vignette 'gggenomes.Rmd' failed with diagnostics:
> ℹ In index: 1.
> ℹ With name: PSSP7.
> Caused by error in `open.connection()`:
> ! Timeout was reached: [[ftp.ncbi.nlm.nih.gov](ftp://ftp.ncbi.nlm.nih.gov/)] Connection time-out

**Comment by iimog** [comment]
At least we have until tomorrow to fix it :grimacing: Let me know if you need help with this.

**Comment by thackl** [comment]
Ah, no, they sent it a few days ago, but I was on vacation :)
