### ISSUE TITLE
Can I cite an alpha release version in my paper

### ISSUE THREAD

**Issue by xvtyzn** [thackl/gggenomes#20]
Hi.
Thank you very much for developing useful software. 

gggenomes is currently in alpha release (0.0.0.9000) but is it possible to cite it in a paper using the current package?
> Thomas Hackl and Markus J. Ankenbrand (2020). gggenomes: A Grammar of Graphics for Comparative Genomics. R package version 0.0.0.9000. https://github.com/thackl/gggenomes

gggenomes make my bacterial genome data very interpretable using the example code.
It is very cool that the protein domain label can be shown in comparative genomics results!

If you do not recommend using it yet, I would consider using another software.

**Comment by thackl** [comment]
Happy to hear that gggenomes help you with your analysis. Sure, you can cite the current version from the webpage. Hopefully, we will have a preprint out in a few weeks to make citation easier.
