### ISSUE TITLE
Visualisation of restriction enzyme sites on plasmid seq.

### ISSUE THREAD

**Issue by xvtyzn** [thackl/gggenomes#205]
Hi!

I am interested in a method for visualising restriction enzyme sites on plasmids.
What functions could be used to achieve this aim?

The image I have in mind is a visualisation like Fig. 1 at the following URL.
[Visualisation of restriction enzyme sites on the genome](https://researchguides.library.vanderbilt.edu/c.php?g=69346&p=818402)

Thank you in advance.

Best,

Keigo

**Comment by thackl** [comment]
For plasmids, especially if you want them round (polar coordinate system), check out https://github.com/BradyAJohnston/plasmapR. If you want to use gggenomes, something like the following could get you started:

```r
#| fig.height: 2
#| fig.width: 6
library(tidyverse)
library(gggenomes)

s1 <- tibble(seq_id = "pUC19", length = 2686)
g1 <- tibble(seq_id = "pUC19", start = c(100, 1000, 1800), end = c(700, 1400, 2600), name = c("ori", "lacZ", "Apr"))
r1 <- tibble(seq_id = "pUC19", start = sample(1:2686, 50), end = start, name = paste0('re', 1:50))

gggenomes(g1, s1, feats=r1) +
  geom_seq() +
  geom_gene() +
  geom_feat_text(aes(label = "|"), position=position_nudge(y=.1)) +
  geom_feat_text(aes(label = name), position=position_nudge(y=.2), angle=60) +
  geom_gene_tag(aes(label=name))
```
![image](https://github.com/user-attachments/assets/0e24a4cf-ba43-487e-8638-b521236b6909)

And to avoid overplotting, you could use the ggrepel package

```r
#| fig.height: 2
#| fig.width: 6
library(ggrepel)

gggenomes(g1, s1, feats=r1) +
  geom_seq() +
  geom_gene() +
  geom_text_repel(aes(x=x, y=y, label=name), data=feats(), nudge_y = .2, direction="x", size=2, angle=60)
```

![image](https://github.com/user-attachments/assets/e544f885-84c6-4aa2-9706-3f8efc12ca58)

**Comment by xvtyzn** [comment]
This is exactly what I was looking for. Thank you!

Keigo
