### ISSUE TITLE
Add Hmisc package to CI

### ISSUE THREAD

**Issue by thackl** [thackl/gggenomes#61]
For the new [geom_wiggle()](https://thackl.github.io/gggenomes/reference/geom_wiggle.html) function I am using some stats methods from `Hmisc` (which is also used by some ggplot2 stat summary functions). Could you add it to the CI @iimog?

**Comment by iimog** [comment]
Sure, I'll add it. There are two ways to do it:
1. I can add it under `Depends` in `DESCRIPTION`. This way it is also listed as a dependency of `gggenomes` in general.
2. I can just install it in the CI environment. It will not be listed as a dependency of `gggenomes` and users that want to call `geom_wiggle` need to have `Hmisc` installed as well.

Which method do you prefer in this case?

**Comment by thackl** [comment]
In ggplot2 it is only listed in the `DESCRIPTION` as `Suggests`. That's why I meant to put it there for gggenomes as well (which I actually forgot). `geom_wiggle` doesn't require Hmisc. I just use it because it gives nice defaults and I was lazy. But I through an error for users if it is missing including a hint on how to use `geom_wiggle` without Hmisc.. So you tell me :D

**Comment by iimog** [comment]
Oh, forgot to reply here... I think in this case it is best to have it under `Suggests` in `DESCRIPTION` as well and add it to the CI environment manually. I did both. Nice new feature btw!
