### ISSUE TITLE
generating a file like emale_prot_ava

### ISSUE THREAD

**Issue by aleuUH** [thackl/gggenomes#63]
Hello again @thackl

I was wondering how the emale_prot_ava file was generated. I created a blastp file with outfmt 6 and read that in using read_blast() as so:

FR_prot_ava <-read_blast("genes.blastp.tsv")

which looks like this:
FR_prot_ava
# A tibble: 671 x 12
   qaccver                         saccver                          pident length mismatch gapopen qstart  qend sstart  send    evalue bitscore
   <chr>                           <chr>                             <dbl>  <dbl>    <dbl>   <dbl>  <dbl> <dbl>  <dbl> <dbl>     <dbl>    <dbl>
 1 contig_26_pilon_925301_962441_1 contig_1560_pilon_1               100      147        0       0      1   147      5   151 9.58e-112    306  
 2 contig_26_pilon_925301_962441_1 contig_26_pilon_925301_962441_1   100      147        0       0      1   147      1   147 1.21e-111    305  
 3 contig_26_pilon_925301_962441_1 contig_1560_pilon_26               26.2     80       45       3     34   100    141   219 3.8 e-  1     21.9

I seem to missing  the file_id         feat_id         feat_id2 columns. Any tips would be great!

Thanks,
Andy

**Comment by thackl** [comment]
Ah, good question (and not well documented, I have to admit). `read_blast()` reads blast results just in a generic way (as is). To add the missing columns import your blast results with `read_sublinks()` - this tells gggenomes to expect links between genomes, and the 'sub' tells it that ids and coordinates are relative to features (proteins), not sequences (contigs).

This is how I generated `emale_prot_ava`:
`emale_prot_ava <- read_sublinks(ex("emales/emales-prot-ava.o6"))`

**Comment by aleuUH** [comment]
Working now.

Thanks again!
