### ISSUE TITLE
Bug in focus() when supplying loci

### ISSUE THREAD

**Issue by johnomics** [thackl/gggenomes#74]
Thanks for writing gggenomes, it's great. There is a bug in focus():
https://github.com/thackl/gggenomes/blob/a3b92d8934011a7aacd636df860dc4f35f1afa87/R/focus.R#L113

I think this should be `has_name(loci, "locus_id")`. Without it, I am getting the following error when using `focus(.loci = loci)` with a tibble `loci` with bin_id, seq_id, start and end columns:
```
Error : argument "name" is missing, with no default
```

**Comment by thackl** [comment]
Oh, yes, it most certainly is a bug. In fact, the entire conditional code chunk is bs :see_no_evil:. Will push a fix asap.
