### ISSUE TITLE
Seq order (`as.factor`) get lost when `focus()`ing

### ISSUE THREAD

**Issue by iferres** [thackl/gggenomes#83]
Hi, I noticed that the order of sequences (i.e. contigs) get lost when applying `focus`. 
For instance:
```r
library(gggenomes)
library(magrittr)

s0 <- tibble(
  bin_id = c("A", "A", "B", "B", "B", "B"),
  seq_id = factor(c("A1", "A1", "B1", "B1", "B2", "B2"), levels = c("A1", "B2", "B1")), # set factor to order contigs
  feat_id = c("a1","a2","b3", "b4", "b1", "b2"),
  start = c(1, 20, 1, 50, 1, 20),
  end = c(10, 30, 40, 70, 10, 30),
  strand = c(1, 1, 1, 1, 1, 1),
  length = c(1000, 1000, 1000, 1000, 1000, 1000)
)

# works ok
p <- gggenomes(s0) + 
  geom_seq() + 
  geom_gene() + 
  geom_gene_label(aes(label=feat_id)) + 
  geom_seq_label()

```
![imagen](https://user-images.githubusercontent.com/26774127/133297865-1db7d8f6-9a17-4f69-a740-26e1028a96da.png)

```r

# order of contigs (factors) get lost
p %>% focus()
```
![imagen](https://user-images.githubusercontent.com/26774127/133297941-db84b010-1710-4dd2-9013-1e68a0c7729f.png)

Any way of keeping that order?
Thanks!

**Comment by thackl** [comment]
Ha, I'm somewhat surprised the first one works ;). Internally, all IDs are converted to characters because otherwise, I get issues when joining across tables (seqs, genes, ...).

That said, I agree, it would be more intuitive if the order of loci would follow the order of the input sequences. I will modify the code to get that behavior as soon as I have time.

In the meantime, you could reorder your sequences after focus

```
p %>% focus() %>% pick_seqs_within(B2_lc1, B1_lc1)
```

should do the trick

**Comment by iferres** [comment]
Thanks! Another question, what does "_lc1", "_lc2", etc, means or how are they set? Just to automate the pick_seqs_within process. In other words: I'm not sure how the 1 or 2 suffixes are chosen.

**Comment by thackl** [comment]
Ah, I see, makes sense. Yes, might not be trivial to automate `pick_seqs_within`... 

"B2_lc1" is short for "locus #1 on sequence B2". Each locus needs a unique ID, so I just count them per sequence. You can change that, the default pattern is `focus(..., .locus_id = str_glue("{seq_id}_lc{row_number()}"`. You can also play with `focus(..., .locus_id_group=1)` to count loci not per sequence.

But, anyway. I have a few minutes. Let me see if II can push a fix for the order right away!

```
p %>% focus(.locus_id = str_glue("{seq_id}#{row_number()}"))
p %>% focus(.locus_id_group=1, .locus_id = str_glue("locus{row_number()}"))
```
![image](https://user-images.githubusercontent.com/9363087/133311639-d038fda1-307a-44dd-ac85-f62d712d602c.png)
![image](https://user-images.githubusercontent.com/9363087/133311660-da8d5e92-664b-4595-87eb-2cd32747f73a.png)

**Comment by thackl** [comment]
with the latest version
```
p %>% focus()
``` 
![image](https://user-images.githubusercontent.com/9363087/133314288-8176c841-112f-4e01-a360-80cfb035a6f3.png)

**Comment by iferres** [comment]
Genius! Worked like a charm. 
Thanks again
Bests!
